# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/elf/falsecolor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/elf/falsecolor

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/elf/falsecolor/CMakeFiles /home/elf/falsecolor/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/elf/falsecolor/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Distance-optional-lib

# Build rule for target.
Distance-optional-lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Distance-optional-lib
.PHONY : Distance-optional-lib

# fast build rule for target.
Distance-optional-lib/fast:
	$(MAKE) -f CMakeFiles/Distance-optional-lib.dir/build.make CMakeFiles/Distance-optional-lib.dir/build
.PHONY : Distance-optional-lib/fast

#=============================================================================
# Target rules for targets named common-optional-lib

# Build rule for target.
common-optional-lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 common-optional-lib
.PHONY : common-optional-lib

# fast build rule for target.
common-optional-lib/fast:
	$(MAKE) -f CMakeFiles/common-optional-lib.dir/build.make CMakeFiles/common-optional-lib.dir/build
.PHONY : common-optional-lib/fast

#=============================================================================
# Target rules for targets named doc

# Build rule for target.
doc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc
.PHONY : doc

# fast build rule for target.
doc/fast:
	$(MAKE) -f CMakeFiles/doc.dir/build.make CMakeFiles/doc.dir/build
.PHONY : doc/fast

#=============================================================================
# Target rules for targets named edge_detect-optional-lib

# Build rule for target.
edge_detect-optional-lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 edge_detect-optional-lib
.PHONY : edge_detect-optional-lib

# fast build rule for target.
edge_detect-optional-lib/fast:
	$(MAKE) -f CMakeFiles/edge_detect-optional-lib.dir/build.make CMakeFiles/edge_detect-optional-lib.dir/build
.PHONY : edge_detect-optional-lib/fast

#=============================================================================
# Target rules for targets named imginput-optional-lib

# Build rule for target.
imginput-optional-lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 imginput-optional-lib
.PHONY : imginput-optional-lib

# fast build rule for target.
imginput-optional-lib/fast:
	$(MAKE) -f CMakeFiles/imginput-optional-lib.dir/build.make CMakeFiles/imginput-optional-lib.dir/build
.PHONY : imginput-optional-lib/fast

#=============================================================================
# Target rules for targets named rgb-optional-lib

# Build rule for target.
rgb-optional-lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rgb-optional-lib
.PHONY : rgb-optional-lib

# fast build rule for target.
rgb-optional-lib/fast:
	$(MAKE) -f CMakeFiles/rgb-optional-lib.dir/build.make CMakeFiles/rgb-optional-lib.dir/build
.PHONY : rgb-optional-lib/fast

#=============================================================================
# Target rules for targets named shell-optional-lib

# Build rule for target.
shell-optional-lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 shell-optional-lib
.PHONY : shell-optional-lib

# fast build rule for target.
shell-optional-lib/fast:
	$(MAKE) -f CMakeFiles/shell-optional-lib.dir/build.make CMakeFiles/shell-optional-lib.dir/build
.PHONY : shell-optional-lib/fast

#=============================================================================
# Target rules for targets named rgb

# Build rule for target.
rgb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rgb
.PHONY : rgb

# fast build rule for target.
rgb/fast:
	$(MAKE) -f falsecolor/rgb/CMakeFiles/rgb.dir/build.make falsecolor/rgb/CMakeFiles/rgb.dir/build
.PHONY : rgb/fast

#=============================================================================
# Target rules for targets named rgb-lib

# Build rule for target.
rgb-lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rgb-lib
.PHONY : rgb-lib

# fast build rule for target.
rgb-lib/fast:
	$(MAKE) -f falsecolor/rgb/CMakeFiles/rgb-lib.dir/build.make falsecolor/rgb/CMakeFiles/rgb-lib.dir/build
.PHONY : rgb-lib/fast

#=============================================================================
# Target rules for targets named Distance-lib

# Build rule for target.
Distance-lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Distance-lib
.PHONY : Distance-lib

# fast build rule for target.
Distance-lib/fast:
	$(MAKE) -f falsecolor/distance/CMakeFiles/Distance-lib.dir/build.make falsecolor/distance/CMakeFiles/Distance-lib.dir/build
.PHONY : Distance-lib/fast

#=============================================================================
# Target rules for targets named distance

# Build rule for target.
distance: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 distance
.PHONY : distance

# fast build rule for target.
distance/fast:
	$(MAKE) -f falsecolor/distance/CMakeFiles/distance.dir/build.make falsecolor/distance/CMakeFiles/distance.dir/build
.PHONY : distance/fast

#=============================================================================
# Target rules for targets named gerbil_common-lib

# Build rule for target.
gerbil_common-lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gerbil_common-lib
.PHONY : gerbil_common-lib

# fast build rule for target.
gerbil_common-lib/fast:
	$(MAKE) -f falsecolor/gerbil-common/CMakeFiles/gerbil_common-lib.dir/build.make falsecolor/gerbil-common/CMakeFiles/gerbil_common-lib.dir/build
.PHONY : gerbil_common-lib/fast

#=============================================================================
# Target rules for targets named edge_detect

# Build rule for target.
edge_detect: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 edge_detect
.PHONY : edge_detect

# fast build rule for target.
edge_detect/fast:
	$(MAKE) -f falsecolor/edge_detect/CMakeFiles/edge_detect.dir/build.make falsecolor/edge_detect/CMakeFiles/edge_detect.dir/build
.PHONY : edge_detect/fast

#=============================================================================
# Target rules for targets named edge_detect-lib

# Build rule for target.
edge_detect-lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 edge_detect-lib
.PHONY : edge_detect-lib

# fast build rule for target.
edge_detect-lib/fast:
	$(MAKE) -f falsecolor/edge_detect/CMakeFiles/edge_detect-lib.dir/build.make falsecolor/edge_detect/CMakeFiles/edge_detect-lib.dir/build
.PHONY : edge_detect-lib/fast

#=============================================================================
# Target rules for targets named imginput-lib

# Build rule for target.
imginput-lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 imginput-lib
.PHONY : imginput-lib

# fast build rule for target.
imginput-lib/fast:
	$(MAKE) -f falsecolor/imginput/CMakeFiles/imginput-lib.dir/build.make falsecolor/imginput/CMakeFiles/imginput-lib.dir/build
.PHONY : imginput-lib/fast

#=============================================================================
# Target rules for targets named common-lib

# Build rule for target.
common-lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 common-lib
.PHONY : common-lib

# fast build rule for target.
common-lib/fast:
	$(MAKE) -f falsecolor/common/CMakeFiles/common-lib.dir/build.make falsecolor/common/CMakeFiles/common-lib.dir/build
.PHONY : common-lib/fast

#=============================================================================
# Target rules for targets named dist

# Build rule for target.
dist: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dist
.PHONY : dist

# fast build rule for target.
dist/fast:
	$(MAKE) -f falsecolor/similarity_measures/CMakeFiles/dist.dir/build.make falsecolor/similarity_measures/CMakeFiles/dist.dir/build
.PHONY : dist/fast

#=============================================================================
# Target rules for targets named similarity_measures-lib

# Build rule for target.
similarity_measures-lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 similarity_measures-lib
.PHONY : similarity_measures-lib

# fast build rule for target.
similarity_measures-lib/fast:
	$(MAKE) -f falsecolor/similarity_measures/CMakeFiles/similarity_measures-lib.dir/build.make falsecolor/similarity_measures/CMakeFiles/similarity_measures-lib.dir/build
.PHONY : similarity_measures-lib/fast

#=============================================================================
# Target rules for targets named gerbil

# Build rule for target.
gerbil: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gerbil
.PHONY : gerbil

# fast build rule for target.
gerbil/fast:
	$(MAKE) -f shell/CMakeFiles/gerbil.dir/build.make shell/CMakeFiles/gerbil.dir/build
.PHONY : gerbil/fast

#=============================================================================
# Target rules for targets named shell-lib

# Build rule for target.
shell-lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 shell-lib
.PHONY : shell-lib

# fast build rule for target.
shell-lib/fast:
	$(MAKE) -f shell/CMakeFiles/shell-lib.dir/build.make shell/CMakeFiles/shell-lib.dir/build
.PHONY : shell-lib/fast

optional.o: optional.cpp.o
.PHONY : optional.o

# target to build an object file
optional.cpp.o:
	$(MAKE) -f CMakeFiles/Distance-optional-lib.dir/build.make CMakeFiles/Distance-optional-lib.dir/optional.cpp.o
	$(MAKE) -f CMakeFiles/common-optional-lib.dir/build.make CMakeFiles/common-optional-lib.dir/optional.cpp.o
	$(MAKE) -f CMakeFiles/edge_detect-optional-lib.dir/build.make CMakeFiles/edge_detect-optional-lib.dir/optional.cpp.o
	$(MAKE) -f CMakeFiles/imginput-optional-lib.dir/build.make CMakeFiles/imginput-optional-lib.dir/optional.cpp.o
	$(MAKE) -f CMakeFiles/rgb-optional-lib.dir/build.make CMakeFiles/rgb-optional-lib.dir/optional.cpp.o
	$(MAKE) -f CMakeFiles/shell-optional-lib.dir/build.make CMakeFiles/shell-optional-lib.dir/optional.cpp.o
.PHONY : optional.cpp.o

optional.i: optional.cpp.i
.PHONY : optional.i

# target to preprocess a source file
optional.cpp.i:
	$(MAKE) -f CMakeFiles/Distance-optional-lib.dir/build.make CMakeFiles/Distance-optional-lib.dir/optional.cpp.i
	$(MAKE) -f CMakeFiles/common-optional-lib.dir/build.make CMakeFiles/common-optional-lib.dir/optional.cpp.i
	$(MAKE) -f CMakeFiles/edge_detect-optional-lib.dir/build.make CMakeFiles/edge_detect-optional-lib.dir/optional.cpp.i
	$(MAKE) -f CMakeFiles/imginput-optional-lib.dir/build.make CMakeFiles/imginput-optional-lib.dir/optional.cpp.i
	$(MAKE) -f CMakeFiles/rgb-optional-lib.dir/build.make CMakeFiles/rgb-optional-lib.dir/optional.cpp.i
	$(MAKE) -f CMakeFiles/shell-optional-lib.dir/build.make CMakeFiles/shell-optional-lib.dir/optional.cpp.i
.PHONY : optional.cpp.i

optional.s: optional.cpp.s
.PHONY : optional.s

# target to generate assembly for a file
optional.cpp.s:
	$(MAKE) -f CMakeFiles/Distance-optional-lib.dir/build.make CMakeFiles/Distance-optional-lib.dir/optional.cpp.s
	$(MAKE) -f CMakeFiles/common-optional-lib.dir/build.make CMakeFiles/common-optional-lib.dir/optional.cpp.s
	$(MAKE) -f CMakeFiles/edge_detect-optional-lib.dir/build.make CMakeFiles/edge_detect-optional-lib.dir/optional.cpp.s
	$(MAKE) -f CMakeFiles/imginput-optional-lib.dir/build.make CMakeFiles/imginput-optional-lib.dir/optional.cpp.s
	$(MAKE) -f CMakeFiles/rgb-optional-lib.dir/build.make CMakeFiles/rgb-optional-lib.dir/optional.cpp.s
	$(MAKE) -f CMakeFiles/shell-optional-lib.dir/build.make CMakeFiles/shell-optional-lib.dir/optional.cpp.s
.PHONY : optional.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Distance-optional-lib"
	@echo "... common-optional-lib"
	@echo "... doc"
	@echo "... edge_detect-optional-lib"
	@echo "... edit_cache"
	@echo "... imginput-optional-lib"
	@echo "... rebuild_cache"
	@echo "... rgb-optional-lib"
	@echo "... shell-optional-lib"
	@echo "... rgb"
	@echo "... rgb-lib"
	@echo "... Distance-lib"
	@echo "... distance"
	@echo "... gerbil_common-lib"
	@echo "... edge_detect"
	@echo "... edge_detect-lib"
	@echo "... imginput-lib"
	@echo "... common-lib"
	@echo "... dist"
	@echo "... similarity_measures-lib"
	@echo "... gerbil"
	@echo "... shell-lib"
	@echo "... optional.o"
	@echo "... optional.i"
	@echo "... optional.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

